steps:
  mtaBuild:
    script:this
    buildTarget: 'XSA'
  xsDeploy:
    apiUrl: 'https://10.79.9.18:30030'
    org: 'orgname'
    space: 'PROD'
    # credentialsId: 'XS' omitted, 'XS' is the default
    docker:
    dockerImage: '5f84aab33ccd'
    # dockerPullImage: true # default: 'false'. Needs to be set to 'true' in case the image is served from a docker registry
    loginOpts:  '--skip-ssl-validation'
